// File generated by FlutterFire CLI / Firebase configuration
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1rEGGSs0QYg_9lFRPqiJbYOaD7A_cCCY',
    appId: '1:386815138661:web:a6c0dee19779db153c9f8c',
    messagingSenderId: '386815138661',
    projectId: 'realestateappyt',
    authDomain: 'realestateappyt.firebaseapp.com',
    storageBucket: 'realestateappyt.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1rEGGSs0QYg_9lFRPqiJbYOaD7A_cCCY',
    appId: '1:386815138661:android:a6c0dee19779db153c9f8c',
    messagingSenderId: '386815138661',
    projectId: 'realestateappyt',
    storageBucket: 'realestateappyt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1rEGGSs0QYg_9lFRPqiJbYOaD7A_cCCY',
    appId: '1:386815138661:ios:a6c0dee19779db153c9f8c',
    messagingSenderId: '386815138661',
    projectId: 'realestateappyt',
    storageBucket: 'realestateappyt.firebasestorage.app',
    iosBundleId: 'com.example.realEstateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1rEGGSs0QYg_9lFRPqiJbYOaD7A_cCCY',
    appId: '1:386815138661:ios:a6c0dee19779db153c9f8c',
    messagingSenderId: '386815138661',
    projectId: 'realestateappyt',
    storageBucket: 'realestateappyt.firebasestorage.app',
    iosBundleId: 'com.example.realEstateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1rEGGSs0QYg_9lFRPqiJbYOaD7A_cCCY',
    appId: '1:386815138661:web:a6c0dee19779db153c9f8c',
    messagingSenderId: '386815138661',
    projectId: 'realestateappyt',
    authDomain: 'realestateappyt.firebaseapp.com',
    storageBucket: 'realestateappyt.firebasestorage.app',
  );
}
